---
title: "Web-Scraping in Python"
date: 2022-03-27
---
author: Philip Zieser
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A short example on how to scrape a data table from wikipedia.

# social links

github_username:  Philip-Zieser

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
